# Generated by Django 5.2.7 on 2025-11-04 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Malamal Weekly', max_length=200)),
                ('tagline', models.CharField(default='Your trusted online lottery and gaming platform.', max_length=300)),
                ('description', models.TextField(default='Experience the thrill of winning with secure, fair, and exciting games.')),
                ('contact_email', models.EmailField(default='support@malamalweekly.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 1234567890', max_length=20)),
                ('contact_address', models.CharField(default='Mumbai, India', max_length=200)),
                ('support_hours', models.CharField(default='24/7 Support', max_length=100)),
                ('footer_copyright', models.CharField(default='© 2025 Malamal Weekly. All rights reserved.', max_length=200)),
                ('footer_tagline', models.CharField(default='Secure & Licensed Platform', max_length=200)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=50, unique=True)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(default='bi bi-link', help_text='Bootstrap icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Page content (HTML supported)')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True, help_text='Display link in footer')),
                ('footer_section', models.CharField(choices=[('quick_links', 'Quick Links'), ('information', 'Information'), ('none', 'None')], default='information', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order in footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
