# Generated by Django 5.2.7 on 2025-11-02 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_deposit',
            field=models.BooleanField(default=True, help_text='Allow user to make deposit requests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_profile',
            field=models.BooleanField(default=True, help_text='Allow user to edit profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_play_games',
            field=models.BooleanField(default=True, help_text='Allow user to participate in games'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_games',
            field=models.BooleanField(default=True, help_text='Allow user to view game pages'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_leaderboard',
            field=models.BooleanField(default=True, help_text='Allow user to view leaderboard'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_transaction_history',
            field=models.BooleanField(default=True, help_text='Allow user to view transaction history'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_withdraw',
            field=models.BooleanField(default=True, help_text='Allow user to make withdrawal requests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_permission_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permission_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restriction_notes',
            field=models.TextField(blank=True, help_text='Admin notes about user restrictions', null=True),
        ),
    ]
