# Generated by Django 5.2.7 on 2025-11-04 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_banappeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='Aadhar card number', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name as per ID', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/pan/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN card number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selfie_with_id',
            field=models.ImageField(blank=True, help_text='Selfie holding Aadhar/PAN', null=True, upload_to='kyc_documents/selfie/'),
        ),
    ]
