# Generated by Django 5.2.7 on 2025-11-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_aadhar_back_userprofile_aadhar_front_and_more'),
        ('transactions', '0003_currency_currencyconversionlog_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text="User's preferred currency for display and transactions", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='transactions.currency'),
        ),
    ]
