# Generated by Django 5.2.7 on 2025-11-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='gateway_order_id',
            field=models.CharField(blank=True, help_text="Gateway's order/payment ID", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='gateway_payment_id',
            field=models.CharField(blank=True, help_text="Gateway's payment reference", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='payment_response',
            field=models.TextField(blank=True, help_text='Raw gateway response JSON', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gateway fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_order_id',
            field=models.CharField(blank=True, help_text="Gateway's order ID", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_details',
            field=models.TextField(blank=True, help_text='JSON data from gateway', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount + Fees', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this gateway', max_length=100)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('payu', 'PayU'), ('paypal', 'PayPal'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('cashfree', 'Cashfree'), ('instamojo', 'Instamojo'), ('other', 'Other/Custom')], help_text='Payment provider type', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Internal notes about this gateway', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Enable/disable this gateway for users')),
                ('mode', models.CharField(choices=[('test', 'Test Mode'), ('live', 'Live Mode')], default='test', help_text='Test or Live mode', max_length=10)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which gateway appears to users')),
                ('test_api_key', models.CharField(blank=True, help_text='Test API Key', max_length=500, null=True)),
                ('test_api_secret', models.CharField(blank=True, help_text='Test API Secret', max_length=500, null=True)),
                ('test_merchant_id', models.CharField(blank=True, help_text='Test Merchant ID (if required)', max_length=200, null=True)),
                ('test_additional_config', models.TextField(blank=True, help_text='Additional test config as JSON', null=True)),
                ('live_api_key', models.CharField(blank=True, help_text='Live API Key', max_length=500, null=True)),
                ('live_api_secret', models.CharField(blank=True, help_text='Live API Secret', max_length=500, null=True)),
                ('live_merchant_id', models.CharField(blank=True, help_text='Live Merchant ID (if required)', max_length=200, null=True)),
                ('live_additional_config', models.TextField(blank=True, help_text='Additional live config as JSON', null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook signing secret', max_length=500, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook endpoint URL', null=True)),
                ('logo_url', models.URLField(blank=True, help_text='Logo URL for this payment method', null=True)),
                ('button_color', models.CharField(default='#007bff', help_text='Hex color code for payment button', max_length=7)),
                ('min_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum transaction amount', max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=100000.0, help_text='Maximum transaction amount', max_digits=10)),
                ('transaction_fee_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee percentage (0 for none)', max_digits=5)),
                ('transaction_fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed fee amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gateways', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gateways', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='payment_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_requests', to='transactions.paymentgateway'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.paymentgateway'),
        ),
    ]
