# Generated by Django 5.2.7 on 2025-11-04 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_depositrequest_gateway_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, INR)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Full currency name', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, €, ₹)', max_length=10)),
                ('symbol_position', models.CharField(choices=[('before', 'Before Amount'), ('after', 'After Amount')], default='before', help_text='Where to display the symbol', max_length=10)),
                ('decimal_places', models.IntegerField(default=2, help_text='Number of decimal places')),
                ('thousand_separator', models.CharField(default=',', help_text='Separator for thousands', max_length=1)),
                ('decimal_separator', models.CharField(default='.', help_text='Decimal separator', max_length=1)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this currency')),
                ('is_base_currency', models.BooleanField(default=False, help_text='Is this the base currency for exchange rates?')),
                ('display_order', models.IntegerField(default=0, help_text='Order in currency selection dropdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate_used', models.DecimalField(decimal_places=8, max_digits=20)),
                ('transaction_type', models.CharField(help_text='deposit, withdrawal, game_entry, etc.', max_length=50)),
                ('transaction_id', models.IntegerField(blank=True, help_text='Related transaction ID', null=True)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='transactions.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='transactions.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-converted_at'],
                'indexes': [models.Index(fields=['user', 'converted_at'], name='transaction_user_id_6f150c_idx'), models.Index(fields=['transaction_type', 'transaction_id'], name='transaction_transac_574487_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, help_text='Exchange rate (1 from_currency = X to_currency)', max_digits=20)),
                ('source', models.CharField(default='manual', help_text='Source of exchange rate (manual, API, etc.)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this rate becomes effective')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When this rate expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(help_text='Convert from this currency', on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='transactions.currency')),
                ('to_currency', models.ForeignKey(help_text='Convert to this currency', on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='transactions.currency')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'is_active'], name='transaction_from_cu_7a9a80_idx'), models.Index(fields=['effective_from', 'effective_until'], name='transaction_effecti_164111_idx')],
                'unique_together': {('from_currency', 'to_currency', 'effective_from')},
            },
        ),
    ]
