# Generated by Django 5.2.7 on 2025-11-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_currency_currencyconversionlog_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='amount_in_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Deposit currency', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='transactions.currency'),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='base_currency',
            field=models.ForeignKey(blank=True, help_text="Gateway's base currency (usually INR)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_base', to='transactions.currency'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='supported_currencies',
            field=models.ManyToManyField(blank=True, help_text='Currencies supported by this gateway', related_name='payment_gateways', to='transactions.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_in_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in base currency (INR)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Transaction currency', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='amount_in_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Withdrawal currency', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='transactions.currency'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used', max_digits=12, null=True),
        ),
    ]
