# Generated by Django 5.2.7 on 2025-11-01 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game_type', models.CharField(choices=[('number_match', 'Number Match'), ('lucky_draw', 'Lucky Draw'), ('color_game', 'Color Game'), ('custom', 'Custom Game')], max_length=50)),
                ('description', models.TextField()),
                ('rules', models.TextField(help_text='Game rules and instructions')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('entry_fee', models.DecimalField(decimal_places=2, help_text='Credits required to participate', max_digits=10)),
                ('min_participants', models.IntegerField(default=2, help_text='Minimum participants required')),
                ('max_participants', models.IntegerField(default=1000, help_text='Maximum participants allowed')),
                ('winning_amount', models.DecimalField(decimal_places=2, help_text='Prize amount for winner', max_digits=10)),
                ('game_config', models.JSONField(default=dict, help_text='Game-specific configuration like number range, colors, etc.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_rounds_played', models.IntegerField(default=0)),
                ('total_winners', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Open for Entry'), ('closed', 'Entry Closed'), ('processing', 'Processing Results'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('total_participants', models.IntegerField(default=0)),
                ('total_pool_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('winning_combination', models.JSONField(blank=True, help_text='Winning numbers/colors/etc', null=True)),
                ('has_winner', models.BooleanField(default=False)),
                ('result_announced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_rounds', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.game')),
            ],
            options={
                'verbose_name': 'Game Round',
                'verbose_name_plural': 'Game Rounds',
                'ordering': ['-scheduled_start'],
                'unique_together': {('game', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games_played', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('win_rate', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard',
                'ordering': ['-points', '-total_winnings'],
            },
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.JSONField(help_text="User's selected numbers/colors/etc")),
                ('entry_fee_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_winner', models.BooleanField(default=False)),
                ('winning_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prize_claimed', models.BooleanField(default=False)),
                ('prize_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('entry_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='games.gameround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Entry',
                'verbose_name_plural': 'User Entries',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game_round')},
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prize_credited', models.BooleanField(default=False)),
                ('prize_credited_at', models.DateTimeField(blank=True, null=True)),
                ('announced_at', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='games.gameround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnings', to=settings.AUTH_USER_MODEL)),
                ('user_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_record', to='games.userentry')),
            ],
            options={
                'verbose_name': 'Winner',
                'verbose_name_plural': 'Winners',
                'ordering': ['-announced_at'],
            },
        ),
    ]
