# Generated by Django 5.2.7 on 2025-11-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('number_match', 'Number Match'), ('lucky_draw', 'Lucky Draw'), ('color_game', 'Color Game'), ('keno', 'Keno'), ('odd_even', 'Odd/Even'), ('custom', 'Custom Game')], max_length=50),
        ),
    ]
